SET @PLAYER_ID := 'LWJ';
SET @PLAYER_PWD := '1234';
SET @PLAYER_NAME := 'LEEWOONGJAE';

DELETE FROM PLAYER WHERE PLAYER_ID = @PLAYER_ID;

INSERT INTO PLAYER(PLAYER_ID,PLAYER_PWD,PLAYER_NAME)VALUES(@PLAYER_ID,@PLAYER_PWD,@PLAYER_NAME);

SELECT * FROM PLAYER;

SELECT 1 FROM PLAYER WHERE PLAYER_ID = @PLAYER_ID;

UPDATE PLAYER SET PLAYER_NAME = 'KANGHOJAE' WHERE PLAYER_ID = 'LWJ';

SELECT * FROM PLAYER;